# Generated by Django 3.0.3 on 2020-05-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecordClass',
            new_name='AccessRecord',
        ),
    ]
